version: '3.3'

services:
  app:
    build: .
    volumes:
      - ./:/srv/www
    working_dir: /var/www
    links:
      - db
      - redis

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onlyfordev

  redis:
    image: redis:latest

  nginx:
    image: nginx:1.13.12
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/www
    links:
      - app
