version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: dev-dockerfile
    volumes:
      - ./:/srv/www
    working_dir: /var/www
    links:
      - culturegenapi
      - db
      - heraldryapi
      - redis
      - regiongenapi

  culturegenapi:
    image: ironarachne/culturegend:latest

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onlyfordev

  heraldryapi:
    image: ironarachne/armsapi:latest

  redis:
    image: redis:latest

  regiongenapi:
    image: ironarachne/regiongend:latest

  nginx:
    image: nginx:1.13.12
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/www
    links:
      - app
