version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          VERSION_TAG=`cat VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/generators-website:$VERSION_TAG -t ironarachne/generators-website:$GIT_TAG -t ironarachne/generators-website:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/generators-website:$VERSION_TAG
          docker push ironarachne/generators-website:$GIT_TAG
          docker push ironarachne/generators-website:latest
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
