version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ironarachne/generators-website:$TAG -t ironarachne/generators-website:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/generators-website:$TAG
          docker push ironarachne/generators-website:latest